Various

diff --git a/article b/article
--- a/article
+++ b/article
@@ -6,14 +6,23 @@ NAME
 USAGE
   article <Article Title - Words with spaces>
 
+OPTIONS
+  -h|--help
+    Show help text.
+
+  -s <section name>
+    Specify section name.
+
 DESCRIPTION
-  A basic script to create a new article.
+  A basic script to create a new website article.
 
 AUTHOR
-  mjnurse.dev - 2020
+  mjnurse - 2020
 "
 help_line="Creates a new website article: article <title: spaces allowed>"
 web_desc_line="Creates a new website article"
+
+web_home="/c/Users/MartinNurse/OneDrive - Quantexa Ltd/MJN/github/mjnurse-github-io"
 
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo "$help_text"
@@ -22,25 +31,37 @@ fi
 
 if [[ "$1" == "-s" ]]; then
    shift
-   section_name="$1"
+   cd "$web_home"
+   section_name="$(ls -d ${1}* 2>/dev/null)"
+   if [[ "$(echo $section_name | wc -w)" != 1 ]]; then
+      echo "Bad section name: $1"
+      exit
+   fi
    shift
 fi
 
 params=$*
 
+if [[ "$params" == "" ]]; then
+   echo "Article Title missing"
+   exit
+fi
+
 # Prompt for the section
 
-cd /c/MJN/drive/github/mjnurse-github-io || exit
+cd "$web_home" || exit
 if [[ "$section_name" == "" ]]; then
    find . -type d -print | sed "s/^\.//; /^\/[^A-Z]/d; /images$/d; /All-A/d; /^$/d" \
       > /tmp/article.tmp
 
    ((section_num = 1))
    echo SECTIONS:
+   echo ---------
    while read -r line; do
       echo "$section_num: $line"
       (( section_num=section_num + 1 ))
    done < /tmp/article.tmp
+   echo
    read -rp "Select section: " chosen_num
    
    ((section_num = 1))
@@ -52,7 +73,9 @@ if [[ "$section_name" == "" ]]; then
    done < /tmp/article.tmp
 fi
 
-cd /c/MJN/drive/github/mjnurse-github-io/"${section_name}"
+cd "${web_home}/${section_name}"
+echo "FILES IN SECTION"
+echo "----------------"
 ls | sort -f
 filename=${params// /_}.md
 echo ------------------------------
